apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: kubernetes
type: Opaque
data:
  password: ZTEwMDI3MmRiMjZjZWMyMjY3MzUwYTAzOGJkZDg4MjczMjRiYTBjMGFjYTczOTMxY2UyMGExYzM2NjI1MzE4Yg== 
  # this is the base64 encoded value of "mysecretpassword" which we will use as JWT_SECRET in backend deployment to sign our JWT tokens. You can change the value as per your requirement but make sure to encode it in base64 before putting it here. You can use online tools like https://www.base64encode.org/ to encode your string in base64.
